fixtures:
  forge: "https//forge.puppetlabs.com"
  repositories:
    apt:
      repo: 'https://github.com/puppetlabs/puppetlabs-apt.git'
      branch: '1.8.x'
    inifile: "git://github.com/puppetlabs/puppetlabs-inifile.git"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
    blackfire: "#{source_dir}"
