sudo: false
language: ruby
bundler_args: --no-deployment
script:
  - bundle exec rake metadata
  - bundle exec rake syntax
  - bundle exec rake lint
  - bundle exec rake spec
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.5
    env: PUPPET_VERSION="~> 3.7.5"
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 3.4.0"
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 3.0"
