language: ruby
bundler_args: --no-deployment
script:
  - bundle exec rake travis
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.5
    env: PUPPET_VERSION="~> 3.7.0"
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 3.4.0"
